`.github/workflows/ci.yml`:

```yaml
name: CI Процесс

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B clean verify

    - name: Run Checkstyle
      run: mvn checkstyle:check

    - name: Generate Code Coverage
      run: mvn jacoco:report

    - name: Enforce JaCoCo 100% Branch Coverage
      run: |
        COVERAGE=$(grep -A 1 '<counter type="BRANCH"' target/site/jacoco/jacoco.xml | grep -o 'covered="[0-9]*"' | cut -d'"' -f2)
        MISSED=$(grep -A 1 '<counter type="BRANCH"' target/site/jacoco/jacoco.xml | grep -o 'missed="[0-9]*"' | cut -d'"' -f2)
        TOTAL=$((COVERAGE + MISSED))
        if [ "$TOTAL" -eq 0 ] || [ "$COVERAGE" -lt "$TOTAL" ]; then
          echo "Branch coverage is less than 100%."
          exit 1
        fi
